---
rvm:
  - 2.3.1

sudo: true

env:
  APP_VERSION: ${TRAVIS_COMMIT}

services:
  - docker

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y unzip
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - sudo unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin
  - rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - bundle install

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - kitchen create

script:
  - docker build -t gbergere/micro-service-as-code:${TRAVIS_COMMIT} .
  - docker push gbergere/micro-service-as-code:${TRAVIS_COMMIT}
  - kitchen verify

after_script:
  - kitchen destroy
